// src/app/api/export-ppt/route.ts
// Generates a professional PowerPoint presentation from project portfolio data

import { NextResponse } from 'next/server'
// @ts-ignore
import PptxGenJS from 'pptxgenjs'

// NexPlan brand colours
const BRAND = {
  dark:    '0f172a',
  darker:  '060d1b', 
  surface: '1e293b',
  accent:  '00d4ff',
  violet:  '7c3aed',
  green:   '22d3a5',
  amber:   'f59e0b',
  red:     'ef4444',
  text:    'f1f5f9',
  muted:   '94a3b8',
  border:  '334155',
}

function ragColor(rag: string) {
  if (rag === 'green') return BRAND.green
  if (rag === 'amber') return BRAND.amber
  return BRAND.red
}

function ragLabel(rag: string) {
  if (rag === 'green') return '🟢 On Track'
  if (rag === 'amber') return '🟡 Needs Attention'
  return '🔴 At Risk'
}

export async function POST(request: Request) {
  try {
    const { projects, tasks, risks, orgName, generatedBy, aiInsights, workspaces: wsData } = await request.json()

    const pres = new PptxGenJS()
    pres.layout  = 'LAYOUT_16x9'
    pres.author  = generatedBy || 'NexPlan'
    pres.title   = `${orgName || 'Portfolio'} - Project Intelligence Report`
    pres.subject = 'IT Project Management Report'

    const totalTasks   = tasks?.length || 0
    const doneTasks    = tasks?.filter((t: any) => t.status === 'done').length || 0
    const overdueTasks = tasks?.filter((t: any) => t.due_date && new Date(t.due_date) < new Date() && t.status !== 'done').length || 0
    const blockedTasks = tasks?.filter((t: any) => t.status === 'blocked').length || 0
    const pct          = totalTasks > 0 ? Math.round((doneTasks / totalTasks) * 100) : 0
    const today        = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })

    // ── SLIDE 1: Title ─────────────────────────────────────────
    const s1 = pres.addSlide()
    s1.background = { color: BRAND.dark }

    // Gradient bar top
    s1.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.08, fill: { color: BRAND.accent } })

    // Logo text
    s1.addText('✦ NexPlan', {
      x: 0.5, y: 0.3, w: 4, h: 0.5,
      fontSize: 18, bold: true, color: BRAND.accent, fontFace: 'Arial',
    })

    // Main title
    s1.addText('Project Intelligence Report', {
      x: 0.5, y: 1.2, w: 9, h: 1.2,
      fontSize: 44, bold: true, color: BRAND.text, fontFace: 'Arial',
    })

    // Org name
    s1.addText(orgName || 'IT Portfolio', {
      x: 0.5, y: 2.4, w: 9, h: 0.7,
      fontSize: 24, color: BRAND.accent, fontFace: 'Arial',
    })

    // Date + generated by
    s1.addText(`Generated: ${today}  |  Prepared by: ${generatedBy || 'Portfolio Manager'}  |  Powered by NexPlan AI`, {
      x: 0.5, y: 4.8, w: 9, h: 0.4,
      fontSize: 11, color: BRAND.muted, fontFace: 'Arial',
    })

    // Bottom gradient bar
    s1.addShape(pres.ShapeType.rect, { x: 0, y: 5.5, w: '100%', h: 0.12, fill: { color: BRAND.violet } })

    // ── SLIDE 2: Portfolio Summary ─────────────────────────────
    const s2 = pres.addSlide()
    s2.background = { color: BRAND.dark }
    s2.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.08, fill: { color: BRAND.accent } })

    s2.addText('Portfolio Overview', {
      x: 0.5, y: 0.25, w: 9, h: 0.6,
      fontSize: 28, bold: true, color: BRAND.text, fontFace: 'Arial',
    })

    // KPI cards
    const kpis = [
      { label: 'Total Projects', value: String(projects?.length || 0), color: BRAND.accent },
      { label: 'Completion Rate', value: `${pct}%`, color: BRAND.green },
      { label: 'Overdue Tasks', value: String(overdueTasks), color: overdueTasks > 0 ? BRAND.red : BRAND.green },
      { label: 'Blocked Tasks', value: String(blockedTasks), color: blockedTasks > 0 ? BRAND.amber : BRAND.green },
    ]

    kpis.forEach((kpi, i) => {
      const x = 0.3 + i * 2.4
      s2.addShape(pres.ShapeType.rect, {
        x, y: 1.1, w: 2.2, h: 1.4,
        fill: { color: BRAND.surface }, line: { color: kpi.color, width: 1.5 },
      })
      s2.addText(kpi.value, {
        x, y: 1.2, w: 2.2, h: 0.7,
        fontSize: 36, bold: true, color: kpi.color, align: 'center', fontFace: 'Arial',
      })
      s2.addText(kpi.label, {
        x, y: 1.9, w: 2.2, h: 0.4,
        fontSize: 11, color: BRAND.muted, align: 'center', fontFace: 'Arial',
      })
    })

    // Task breakdown bar
    s2.addText('Task Breakdown', {
      x: 0.5, y: 2.8, w: 9, h: 0.4,
      fontSize: 16, bold: true, color: BRAND.text, fontFace: 'Arial',
    })

    const statuses = [
      { label: 'Done', count: doneTasks, color: BRAND.green },
      { label: 'In Progress', count: tasks?.filter((t: any) => t.status === 'in_progress').length || 0, color: BRAND.accent },
      { label: 'Review', count: tasks?.filter((t: any) => t.status === 'review').length || 0, color: BRAND.amber },
      { label: 'Blocked', count: blockedTasks, color: BRAND.red },
      { label: 'Backlog', count: tasks?.filter((t: any) => t.status === 'backlog').length || 0, color: BRAND.border },
    ]

    statuses.forEach((s, i) => {
      const x = 0.3 + i * 1.9
      s2.addShape(pres.ShapeType.rect, {
        x, y: 3.3, w: 1.7, h: 0.25,
        fill: { color: s.color },
      })
      s2.addText(`${s.label}: ${s.count}`, {
        x, y: 3.65, w: 1.7, h: 0.3,
        fontSize: 10, color: BRAND.muted, align: 'center', fontFace: 'Arial',
      })
    })

    // Progress bar
    s2.addShape(pres.ShapeType.rect, { x: 0.5, y: 4.2, w: 9, h: 0.3, fill: { color: BRAND.surface }, line: { color: BRAND.border } })
    if (pct > 0) {
      s2.addShape(pres.ShapeType.rect, { x: 0.5, y: 4.2, w: 9 * pct / 100, h: 0.3, fill: { color: BRAND.green } })
    }
    s2.addText(`Overall Completion: ${pct}% (${doneTasks} of ${totalTasks} tasks done)`, {
      x: 0.5, y: 4.6, w: 9, h: 0.3,
      fontSize: 12, color: BRAND.muted, fontFace: 'Arial',
    })

    s2.addShape(pres.ShapeType.rect, { x: 0, y: 5.5, w: '100%', h: 0.12, fill: { color: BRAND.violet } })

    // ── SLIDE 3: Project Health Scores ─────────────────────────
    const s3 = pres.addSlide()
    s3.background = { color: BRAND.dark }
    s3.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.08, fill: { color: BRAND.accent } })

    s3.addText('Project Health Scores', {
      x: 0.5, y: 0.25, w: 9, h: 0.6,
      fontSize: 28, bold: true, color: BRAND.text, fontFace: 'Arial',
    })

    const projectList = projects || []
    const wsList      = wsData   || []
    // Show workspaces if available, otherwise fall back to projects
    const rowData = wsList.length > 0 ? wsList : projectList
    const maxRows = Math.min(rowData.length, 8)

    rowData.slice(0, maxRows).forEach((p: any, i: number) => {
      const y = 1.1 + i * 0.52
      const rag = p.rag || 'green'
      const score = p.score || 80
      const col = ragColor(rag)

      // RAG dot
      s3.addShape(pres.ShapeType.ellipse, { x: 0.3, y: y + 0.1, w: 0.25, h: 0.25, fill: { color: col } })

      // Workspace/Project name
      const rowLabel = p.client_name
        ? `${p.name} - ${p.client_name}`
        : (p.clientName ? `${p.name} - ${p.clientName}` : p.name || 'Unnamed')
      s3.addText(rowLabel.substring(0, 45), {
        x: 0.7, y, w: 4.5, h: 0.45,
        fontSize: 13, color: BRAND.text, fontFace: 'Arial', bold: true,
      })

      // Progress bar background
      s3.addShape(pres.ShapeType.rect, { x: 5.3, y: y + 0.1, w: 3, h: 0.22, fill: { color: BRAND.surface } })
      // Progress bar fill
      s3.addShape(pres.ShapeType.rect, { x: 5.3, y: y + 0.1, w: 3 * (score / 100), h: 0.22, fill: { color: col } })

      // Score
      s3.addText(`${score}/100`, {
        x: 8.4, y, w: 1.2, h: 0.45,
        fontSize: 13, color: col, bold: true, align: 'right', fontFace: 'Arial',
      })
    })

    s3.addShape(pres.ShapeType.rect, { x: 0, y: 5.5, w: '100%', h: 0.12, fill: { color: BRAND.violet } })

    // ── SLIDE 4: Risk Alerts ───────────────────────────────────
    const s4 = pres.addSlide()
    s4.background = { color: BRAND.dark }
    s4.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.08, fill: { color: BRAND.red } })

    s4.addText('⚠️ Risk Alerts & Issues', {
      x: 0.5, y: 0.25, w: 9, h: 0.6,
      fontSize: 28, bold: true, color: BRAND.text, fontFace: 'Arial',
    })

    const riskAlerts: string[] = []
    if (overdueTasks > 0) riskAlerts.push(`🔴 ${overdueTasks} overdue task${overdueTasks > 1 ? 's' : ''} require immediate attention`)
    if (blockedTasks > 0) riskAlerts.push(`🟡 ${blockedTasks} blocked task${blockedTasks > 1 ? 's' : ''} waiting on dependencies`)

    projectList.forEach((p: any) => {
      if (p.rag === 'red') riskAlerts.push(`🔴 "${p.name}" is at critical risk — health score ${p.score || 0}/100`)
      if (p.rag === 'amber') riskAlerts.push(`🟡 "${p.name}" needs attention`)
    })

    // Add risks from register
    const openRisks = (risks || []).filter((r: any) => r.rag_status === 'red' && r.status === 'open')
    openRisks.slice(0, 3).forEach((r: any) => {
      riskAlerts.push(`🔴 Risk Register: "${r.title}" — ${r.rag_status?.toUpperCase()}`)
    })

    if (riskAlerts.length === 0) {
      riskAlerts.push('✅ No critical risks detected at this time')
    }

    riskAlerts.slice(0, 8).forEach((alert, i) => {
      const y = 1.1 + i * 0.52
      const isRed = alert.startsWith('🔴')
      s4.addShape(pres.ShapeType.rect, {
        x: 0.3, y, w: 9.4, h: 0.42,
        fill: { color: isRed ? 'ef444420' : 'f59e0b20' },
        line: { color: isRed ? BRAND.red : BRAND.amber, width: 0.75 },
      })
      s4.addText(alert, {
        x: 0.5, y: y + 0.05, w: 9, h: 0.35,
        fontSize: 13, color: isRed ? BRAND.red : BRAND.amber, fontFace: 'Arial',
      })
    })

    s4.addShape(pres.ShapeType.rect, { x: 0, y: 5.5, w: '100%', h: 0.12, fill: { color: BRAND.violet } })

    // ── SLIDE 5: AI Insights (if available) ────────────────────
    if (aiInsights) {
      const s5 = pres.addSlide()
      s5.background = { color: BRAND.dark }
      s5.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.08, fill: { color: BRAND.violet } })

      s5.addText('🤖 AI Intelligence Summary', {
        x: 0.5, y: 0.25, w: 9, h: 0.6,
        fontSize: 28, bold: true, color: BRAND.text, fontFace: 'Arial',
      })

      s5.addText('Powered by Claude AI — NexPlan', {
        x: 0.5, y: 0.85, w: 9, h: 0.3,
        fontSize: 11, color: BRAND.muted, fontFace: 'Arial', italic: true,
      })

      s5.addShape(pres.ShapeType.rect, {
        x: 0.3, y: 1.2, w: 9.4, h: 4.1,
        fill: { color: BRAND.surface }, line: { color: BRAND.violet, width: 1 },
      })

      // Clean up markdown formatting for PPT
      const cleanInsights = aiInsights
        .replace(/\*\*/g, '')
        .replace(/#{1,3} /g, '')
        .trim()

      s5.addText(cleanInsights, {
        x: 0.5, y: 1.3, w: 9, h: 3.9,
        fontSize: 12, color: BRAND.text, fontFace: 'Arial',
        valign: 'top', wrap: true,
      })

      s5.addShape(pres.ShapeType.rect, { x: 0, y: 5.5, w: '100%', h: 0.12, fill: { color: BRAND.violet } })
    }

    // ── SLIDE 6: Individual Project Detail ─────────────────────
    projectList.slice(0, 6).forEach((p: any) => {
      const ps = pres.addSlide()
      ps.background = { color: BRAND.dark }
      const col = ragColor(p.rag || 'green')
      ps.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.08, fill: { color: col } })

      ps.addText(p.name || 'Project', {
        x: 0.5, y: 0.25, w: 8, h: 0.6,
        fontSize: 26, bold: true, color: BRAND.text, fontFace: 'Arial',
      })

      ps.addText(ragLabel(p.rag || 'green'), {
        x: 0.5, y: 0.85, w: 4, h: 0.35,
        fontSize: 14, color: col, fontFace: 'Arial', bold: true,
      })

      const projTasks = tasks?.filter((t: any) => t.project_id === p.id) || []
      const pDone     = projTasks.filter((t: any) => t.status === 'done').length
      const pOver     = projTasks.filter((t: any) => t.due_date && new Date(t.due_date) < new Date() && t.status !== 'done').length
      const pBlocked  = projTasks.filter((t: any) => t.status === 'blocked').length
      const pPct      = projTasks.length > 0 ? Math.round((pDone / projTasks.length) * 100) : 0

      // Stats
      const pStats = [
        { label: 'Tasks', value: String(projTasks.length), col: BRAND.accent },
        { label: 'Done', value: String(pDone), col: BRAND.green },
        { label: 'Overdue', value: String(pOver), col: pOver > 0 ? BRAND.red : BRAND.muted },
        { label: 'Blocked', value: String(pBlocked), col: pBlocked > 0 ? BRAND.amber : BRAND.muted },
      ]

      pStats.forEach((stat, i) => {
        const x = 0.3 + i * 2.4
        ps.addShape(pres.ShapeType.rect, { x, y: 1.4, w: 2.2, h: 1.1, fill: { color: BRAND.surface }, line: { color: stat.col, width: 1 } })
        ps.addText(stat.value, { x, y: 1.5, w: 2.2, h: 0.55, fontSize: 32, bold: true, color: stat.col, align: 'center', fontFace: 'Arial' })
        ps.addText(stat.label, { x, y: 2.05, w: 2.2, h: 0.3, fontSize: 11, color: BRAND.muted, align: 'center', fontFace: 'Arial' })
      })

      // Progress bar
      ps.addText(`Completion: ${pPct}%`, { x: 0.5, y: 2.7, w: 9, h: 0.3, fontSize: 13, color: BRAND.text, fontFace: 'Arial', bold: true })
      ps.addShape(pres.ShapeType.rect, { x: 0.5, y: 3.05, w: 9, h: 0.28, fill: { color: BRAND.surface } })
      if (pPct > 0) ps.addShape(pres.ShapeType.rect, { x: 0.5, y: 3.05, w: 9 * pPct / 100, h: 0.28, fill: { color: col } })

      // Dates
      if (p.start_date || p.end_date) {
        ps.addText(
          `📅 ${p.start_date ? new Date(p.start_date).toLocaleDateString('en-GB') : '—'} → ${p.end_date ? new Date(p.end_date).toLocaleDateString('en-GB') : '—'}`,
          { x: 0.5, y: 3.5, w: 5, h: 0.35, fontSize: 12, color: BRAND.muted, fontFace: 'Arial' }
        )
      }

      // Recent tasks
      if (projTasks.length > 0) {
        ps.addText('Recent Tasks', { x: 0.5, y: 3.95, w: 9, h: 0.3, fontSize: 13, bold: true, color: BRAND.text, fontFace: 'Arial' })
        projTasks.slice(0, 3).forEach((t: any, ti: number) => {
          const tc = t.status === 'done' ? BRAND.green : t.status === 'blocked' ? BRAND.red : BRAND.accent
          ps.addText(`${t.title} - ${t.status.replace('_', ' ')}`, {
            x: 0.7, y: 4.3 + ti * 0.3, w: 8.8, h: 0.28,
            fontSize: 11, color: tc, fontFace: 'Arial',
          })
        })
      }

      ps.addShape(pres.ShapeType.rect, { x: 0, y: 5.5, w: '100%', h: 0.12, fill: { color: BRAND.violet } })
    })

    // ── SLIDE LAST: Thank You ──────────────────────────────────
    const sEnd = pres.addSlide()
    sEnd.background = { color: BRAND.darker }
    sEnd.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.08, fill: { color: BRAND.accent } })

    sEnd.addText('✦ NexPlan', { x: 0.5, y: 1.5, w: 9, h: 0.7, fontSize: 40, bold: true, color: BRAND.accent, align: 'center', fontFace: 'Arial' })
    sEnd.addText('AI-Powered IT Project Management', { x: 0.5, y: 2.3, w: 9, h: 0.5, fontSize: 20, color: BRAND.muted, align: 'center', fontFace: 'Arial' })
    sEnd.addText('nexplan.io', { x: 0.5, y: 3.0, w: 9, h: 0.4, fontSize: 16, color: BRAND.violet, align: 'center', fontFace: 'Arial' })
    sEnd.addText(`Report generated: ${today}`, { x: 0.5, y: 4.5, w: 9, h: 0.3, fontSize: 12, color: BRAND.muted, align: 'center', fontFace: 'Arial' })
    sEnd.addShape(pres.ShapeType.rect, { x: 0, y: 5.5, w: '100%', h: 0.12, fill: { color: BRAND.violet } })

    // ── Generate file ──────────────────────────────────────────
    const buffer = await pres.write({ outputType: 'nodebuffer' }) as Buffer
    const uint8 = new Uint8Array(buffer)

    return new NextResponse(uint8, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'Content-Disposition': `attachment; filename="NexPlan-Portfolio-Report-${new Date().toISOString().split('T')[0]}.pptx"`,
      },
    })

  } catch (err: any) {
    console.error('[export-ppt]', err)
    return NextResponse.json({ error: err.message }, { status: 500 })
  }
}
