import { NextResponse } from 'next/server'

export async function POST(request: Request) {
  try {
    const { emails, projectName, report, txtContent, frequency } = await request.json()

    const ragColors: Record<string, string> = {
      red: '#ef4444', amber: '#f59e0b', green: '#22d3a5'
    }
    const ragColor = ragColors[report.overall_rag] || '#00d4ff'

    const htmlReport = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#0d1117;font-family:Arial,sans-serif;">
  <div style="max-width:640px;margin:0 auto;background:#0d1117;padding:24px;">

    <!-- Header -->
    <div style="text-align:center;margin-bottom:24px;">
      <h1 style="color:#00d4ff;font-size:28px;margin:0;letter-spacing:-1px;">NexPlan</h1>
      <p style="color:#6b7280;font-size:12px;margin:4px 0 0;">IT Project Management</p>
    </div>

    <!-- RAG Banner -->
    <div style="background:${ragColor};border-radius:16px;padding:24px;margin-bottom:16px;">
      <p style="color:rgba(255,255,255,0.7);font-size:11px;letter-spacing:2px;text-transform:uppercase;margin:0 0 4px;">${report.period_label}</p>
      <h2 style="color:white;font-size:22px;margin:0 0 8px;">${projectName}</h2>
      <p style="color:rgba(255,255,255,0.85);font-size:14px;margin:0 0 16px;">${report.executive_summary}</p>
      <div style="display:inline-block;background:rgba(255,255,255,0.2);border-radius:10px;padding:10px 20px;text-align:center;">
        <p style="color:rgba(255,255,255,0.8);font-size:11px;margin:0 0 2px;text-transform:uppercase;">Overall Status</p>
        <p style="color:white;font-size:18px;font-weight:bold;margin:0;">${report.overall_rag.toUpperCase()} — ${report.overall_health}</p>
      </div>
    </div>

    <!-- Health Grid -->
    <div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:8px;margin-bottom:16px;">
      ${[['Overall',report.overall_health],['Schedule',report.schedule_status],['Budget',report.budget_status],['Scope',report.scope_status]].map(([l,v]) => `
      <div style="background:#161b22;border-radius:10px;padding:12px;text-align:center;">
        <p style="color:#6b7280;font-size:10px;margin:0 0 4px;text-transform:uppercase;">${l}</p>
        <p style="color:${v==='On Track'?'#22d3a5':v.includes('Risk')||v.includes('Pending')?'#f59e0b':'#ef4444'};font-size:12px;font-weight:bold;margin:0;">${v}</p>
      </div>`).join('')}
    </div>

    <!-- Accomplishments -->
    <div style="background:#161b22;border-radius:12px;padding:16px;margin-bottom:12px;">
      <p style="color:#22d3a5;font-size:13px;font-weight:bold;margin:0 0 10px;">✅ Accomplishments</p>
      ${report.accomplishments.map((a: string) => `<p style="color:#9ca3af;font-size:13px;margin:0 0 6px;padding-left:12px;">• ${a}</p>`).join('')}
    </div>

    <!-- In Progress -->
    <div style="background:#161b22;border-radius:12px;padding:16px;margin-bottom:12px;">
      <p style="color:#00d4ff;font-size:13px;font-weight:bold;margin:0 0 10px;">⚡ In Progress</p>
      ${report.in_progress.map((a: string) => `<p style="color:#9ca3af;font-size:13px;margin:0 0 6px;padding-left:12px;">• ${a}</p>`).join('')}
    </div>

    ${report.blockers.length > 0 ? `
    <!-- Blockers -->
    <div style="background:#2d0c0c;border:1px solid rgba(239,68,68,0.3);border-radius:12px;padding:16px;margin-bottom:12px;">
      <p style="color:#ef4444;font-size:13px;font-weight:bold;margin:0 0 10px;">🚫 Blockers / Escalations</p>
      ${report.blockers.map((b: string) => `<p style="color:#9ca3af;font-size:13px;margin:0 0 6px;padding-left:12px;">⚠ ${b}</p>`).join('')}
    </div>` : ''}

    <!-- Next Period -->
    <div style="background:#161b22;border-radius:12px;padding:16px;margin-bottom:12px;">
      <p style="color:#7c3aed;font-size:13px;font-weight:bold;margin:0 0 10px;">🎯 Next Period Plan</p>
      ${report.next_period_plan.map((a: string) => `<p style="color:#9ca3af;font-size:13px;margin:0 0 6px;padding-left:12px;">→ ${a}</p>`).join('')}
    </div>

    <!-- Risks -->
    <div style="background:#2d1f06;border:1px solid rgba(245,158,11,0.3);border-radius:12px;padding:16px;margin-bottom:24px;">
      <p style="color:#f59e0b;font-size:13px;font-weight:bold;margin:0 0 8px;">⚠️ Risks & Issues</p>
      <p style="color:#9ca3af;font-size:13px;margin:0;">${report.risks_summary}</p>
    </div>

    <!-- Footer -->
    <div style="text-align:center;border-top:1px solid #30363d;padding-top:16px;">
      <p style="color:#6b7280;font-size:11px;margin:0;">Generated by <a href="https://nexplan.io" style="color:#00d4ff;text-decoration:none;">NexPlan</a> · ${frequency.charAt(0).toUpperCase()+frequency.slice(1)} Status Report</p>
    </div>
  </div>
</body>
</html>`

    // Send to all stakeholders
    const sendPromises = emails.map((email: string) =>
      fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${process.env.RESEND_API_KEY}`,
        },
        body: JSON.stringify({
          from: 'NexPlan <info@nexplan.io>',
          to: email,
          subject: `[${report.overall_rag.toUpperCase()}] ${projectName} — ${report.period_label}`,
          html: htmlReport,
          attachments: [{
            filename: `${projectName.replace(/\s+/g,'-')}-Status-Report.txt`,
            content: Buffer.from(txtContent).toString('base64'),
          }],
        }),
      })
    )

    await Promise.all(sendPromises)
    return NextResponse.json({ success: true, sent: emails.length })
  } catch (err: any) {
    console.error('Send status report error:', err)
    return NextResponse.json({ error: err.message }, { status: 500 })
  }
}
